<a href="https://colab.research.google.com/github/Sehaj1904/Data-Science/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
arr = np.zeros(10, dtype='int32')

In [ ]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
arr = np.ones(10)

In [ ]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones(10)*5

In [ ]:
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
arr = np.arange(10,51)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr = np.arange(10,51,2)

In [ ]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
arr = np.arange(12)

In [ ]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr = np.identity(3,dtype="int32")

In [ ]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [ ]:
arr = np.random.rand(1)      
print(arr)

[0.05759313]


In [ ]:
arr = np.random.randn(25)
arr

array([ 0.47385562, -1.45466213, -0.2358294 ,  0.34183817,  0.41969957,
        0.31211319,  0.76026627, -0.26972142, -0.42752872,  0.46745091,
        0.52167315,  1.43589054,  0.41429495,  0.55715446,  1.43329373,
        0.3048935 , -1.61231497, -0.77483373,  1.29848192,  1.99966019,
        1.60013286, -0.49790986,  0.54018424,  0.77227299,  0.34452496])

In [ ]:
arr = np.arange(0.01,1.01,0.01).reshape(10,10)
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
ar = (np.arange(25)+1).reshape(5,5)
ar 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ar[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
ar[2:5:,3:0:-1]

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

In [ ]:
ar[4:1:-1,3:0:-1]

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

In [ ]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar = np.split(ar,[3,5,5])  

In [ ]:
ar

[array([2, 3, 4]), array([5, 6]), array([], dtype=int64), array([7, 8, 9])]

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

In [ ]:
result = np.concatenate([a,b])

In [ ]:
result 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

In [ ]:
result = np.concatenate([a,b],axis = 1)

In [ ]:
result

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

In [ ]:
ar = np.round(np.random.rand(10)*10)
ar

array([1., 9., 9., 2., 7., 6., 7., 4., 5., 4.])

In [ ]:
ar<10
ar[ar<10]

array([1., 9., 9., 2., 7., 6., 7., 4., 5., 4.])

In [ ]:
ar = ar[(ar>2) & (ar<12)]
ar

array([9., 9., 7., 6., 7., 4., 5., 4.])

In [ ]:
arr = np.round(np.random.rand(10)*10)
arr

array([1., 6., 1., 8., 1., 3., 8., 6., 3., 6.])

In [ ]:
arr = np.where(arr == arr.min(),1,0)
arr.sum()

3

In [ ]:
arr = np.arange(20)

In [ ]:
arr = np.where(arr<15,2.0,-5.0)
arr

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2., -5., -5., -5., -5., -5.])

In [ ]:
mat = np.array(
    [[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]]
)
mat

array([[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]])

In [ ]:
print(np.min(mat))
print(np.max(mat))
print(np.sum(mat))

1.0
99.0
2124.0


In [ ]:
print(mat.std())

30.531452634946806


In [ ]:
mat.sum(axis = 0)

array([347., 151., 254., 245., 232., 196., 237., 188., 214.,  60.])

In [ ]:
arr = np.arange(100).reshape(4,5,5)
dim = arr.shape

In [ ]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])